WIDTH = 1000
HEIGHT = 800

# ===== PARTICLE SIZES =====
GRAVITY_STRENGTH = 120
QUARK_RADIUS = 8
NUCLEON_RADIUS = 12
ELECTRON_RADIUS = 5
ATOM_RADIUS = 20
HYDROGEN_RADIUS = 15

# ===== PARTICLE COUNTS =====
NUM_QUARKS = 20
NUM_ELECTRONS = 10

# ===== MERGE MECHANICS =====
MERGE_DISTANCE = 30
MERGE_SPEED_THRESHOLD = 12

# ===== PHYSICS MULTIPLIERS =====
NUCLEON_ATTRACTION_MULTIPLIER = 1.75
QUARK_ATTRACTION_MULTIPLIER = 1.0
optimal_speed_quarks = 2

# ===== FONTS =====

TITLE_FONT = "Verdana"
TITLE_FONT_SIZE = 24
TEXT_FONT = "Arial"
TEXT_FONT_SIZE = 18