#====== Window Info =====
WIDTH = 1000
HEIGHT = 700

#====== Border Info =====
#The Radius is only 40% of the height
BORDER_RADIUS = HEIGHT/2 * 1.3
OUTER_BORDER_RADIUS = BORDER_RADIUS * 9.
BORDER_COLOR = (200,250,250)

BORDER_THICKNESS = 20
OUTER_BORDER_THICKNESS = 5200

# ===== PARTICLE SIZES =====
GRAVITY_STRENGTH = 120
QUARK_RADIUS = 8
NUCLEON_RADIUS = 12
ELECTRON_RADIUS = 5
ATOM_RADIUS = 20
HYDROGEN_RADIUS = 15

# ===== PARTICLE COUNTS =====
NUM_QUARKS = 10

# ===== MERGE MECHANICS =====
MERGE_DISTANCE = 15
MERGE_SPEED_THRESHOLD = 12

# ===== PHYSICS MULTIPLIERS =====
NUCLEON_ATTRACTION_MULTIPLIER = 1.75
QUARK_ATTRACTION_MULTIPLIER = 1.0
optimal_speed_quarks = 2

# ===== FONTS =====

TITLE_FONT = "Verdana"
TITLE_FONT_SIZE = 24
TEXT_FONT = "Arial"
TEXT_FONT_SIZE = 18

# ===== Camera =====
DEFAULT_ZOOM = 1.0
ZOOM_MIN = 0.3
ZOOM_MAX = 5.0
ZOOM_STEP = 1.03


DISTANCE_MULTIPLIER = 0.6
MAX_OFFSET = 1200
RESPONSIVENESS = 0.05